// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: test/proto/recursive-reference/recursive.proto

package recursive_reference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Foo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bars []*Bar `protobuf:"bytes,2,rep,name=bars,proto3" json:"bars,omitempty"`
}

func (x *Foo) Reset() {
	*x = Foo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_recursive_reference_recursive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_recursive_reference_recursive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_test_proto_recursive_reference_recursive_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Foo) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

type Bar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarId string `protobuf:"bytes,1,opt,name=bar_id,json=barId,proto3" json:"bar_id,omitempty"`
	Foo   *Foo   `protobuf:"bytes,2,opt,name=foo,proto3" json:"foo,omitempty"`
}

func (x *Bar) Reset() {
	*x = Bar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_recursive_reference_recursive_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_recursive_reference_recursive_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_test_proto_recursive_reference_recursive_proto_rawDescGZIP(), []int{1}
}

func (x *Bar) GetBarId() string {
	if x != nil {
		return x.BarId
	}
	return ""
}

func (x *Bar) GetFoo() *Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

var File_test_proto_recursive_reference_recursive_proto protoreflect.FileDescriptor

var file_test_proto_recursive_reference_recursive_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x63,
	0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x2d, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x2f, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x65, 0x63,
	0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x5e, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x47, 0x0a, 0x04, 0x62, 0x61, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x72, 0x52, 0x04, 0x62, 0x61, 0x72, 0x73,
	0x22, 0x63, 0x0a, 0x03, 0x42, 0x61, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x61, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x61, 0x72, 0x49, 0x64, 0x12, 0x45,
	0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6a, 0x73,
	0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69,
	0x76, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x46, 0x6f, 0x6f,
	0x52, 0x03, 0x66, 0x6f, 0x6f, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x78, 0x6c, 0x69, 0x6d, 0x6f, 0x2f, 0x67, 0x6f, 0x2d, 0x6a, 0x73,
	0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69,
	0x76, 0x65, 0x2d, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_proto_recursive_reference_recursive_proto_rawDescOnce sync.Once
	file_test_proto_recursive_reference_recursive_proto_rawDescData = file_test_proto_recursive_reference_recursive_proto_rawDesc
)

func file_test_proto_recursive_reference_recursive_proto_rawDescGZIP() []byte {
	file_test_proto_recursive_reference_recursive_proto_rawDescOnce.Do(func() {
		file_test_proto_recursive_reference_recursive_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_recursive_reference_recursive_proto_rawDescData)
	})
	return file_test_proto_recursive_reference_recursive_proto_rawDescData
}

var file_test_proto_recursive_reference_recursive_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_proto_recursive_reference_recursive_proto_goTypes = []interface{}{
	(*Foo)(nil), // 0: jsonrpc.gateway.test.proto.recursive_reference.Foo
	(*Bar)(nil), // 1: jsonrpc.gateway.test.proto.recursive_reference.Bar
}
var file_test_proto_recursive_reference_recursive_proto_depIdxs = []int32{
	1, // 0: jsonrpc.gateway.test.proto.recursive_reference.Foo.bars:type_name -> jsonrpc.gateway.test.proto.recursive_reference.Bar
	0, // 1: jsonrpc.gateway.test.proto.recursive_reference.Bar.foo:type_name -> jsonrpc.gateway.test.proto.recursive_reference.Foo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_proto_recursive_reference_recursive_proto_init() }
func file_test_proto_recursive_reference_recursive_proto_init() {
	if File_test_proto_recursive_reference_recursive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_recursive_reference_recursive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_recursive_reference_recursive_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_recursive_reference_recursive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_recursive_reference_recursive_proto_goTypes,
		DependencyIndexes: file_test_proto_recursive_reference_recursive_proto_depIdxs,
		MessageInfos:      file_test_proto_recursive_reference_recursive_proto_msgTypes,
	}.Build()
	File_test_proto_recursive_reference_recursive_proto = out.File
	file_test_proto_recursive_reference_recursive_proto_rawDesc = nil
	file_test_proto_recursive_reference_recursive_proto_goTypes = nil
	file_test_proto_recursive_reference_recursive_proto_depIdxs = nil
}
