// Code generated by protoc-gen-jsonrpc-gateway. DO NOT EDIT.
// source: test/proto/hello.proto

// Package proto is a reverse proxy.

// It translates gRPC into JSON-RPC APIs.
package proto

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/yxlimo/go-jsonrpc-gateway/jsonrpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = metadata.Join
var _ = json.Marshal
var _ = jsonrpc.NewHTTPServerConn

func request_Greet_Hello_jsonrpc(ctx context.Context, marshaler runtime.Marshaler, client GreetClient, raw json.RawMessage) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HelloRequest
	var metadata runtime.ServerMetadata
	if err := marshaler.NewDecoder(bytes.NewReader(raw)).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.Hello(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func request_Greet_SendMyGift_jsonrpc(ctx context.Context, marshaler runtime.Marshaler, client GreetClient, raw json.RawMessage) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq SendMyGiftRequest
	var metadata runtime.ServerMetadata
	if err := marshaler.NewDecoder(bytes.NewReader(raw)).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.SendMyGift(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func request_Greet_Hello2_jsonrpc(ctx context.Context, marshaler runtime.Marshaler, client GreetClient, raw json.RawMessage) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HelloRequest
	var metadata runtime.ServerMetadata
	if err := marshaler.NewDecoder(bytes.NewReader(raw)).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.Hello2(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

// RegisterGreetJSONRPCHandlerFromEndpoint is same as RegisterGreetJSONRPCHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterGreetJSONRPCHandlerFromEndpoint(ctx context.Context, mux *jsonrpc.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterGreetJSONRPCHandler(ctx, mux, conn)
}

// RegisterGreetJSONRPCHandler registers the http handlers for service Greet to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterGreetJSONRPCHandler(ctx context.Context, mux *jsonrpc.ServeMux, conn *grpc.ClientConn) error {
	return RegisterGreetJSONRPCHandlerClient(ctx, mux, NewGreetClient(conn))
}

// RegisterGreetJSONRPCHandlerClient registers the http handlers for service Greet
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "GreetClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "GreetClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "GreetClient" to call the correct interceptors.
func RegisterGreetJSONRPCHandlerClient(ctx context.Context, mux *jsonrpc.ServeMux, client GreetClient) error {

	mux.Register("Greet.Hello", func(req *http.Request, marshaller runtime.Marshaler, rawBody json.RawMessage) (json.RawMessage, context.Context, error) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var err error
		ctx, err = runtime.AnnotateContext(ctx, mux.RuntimeMux(), req, "/proto.Greet/Hello")
		if err != nil {
			return nil, ctx, err
		}
		resp, md, err := request_Greet_Hello_jsonrpc(ctx, marshaller, client, rawBody)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			return nil, ctx, err
		}
		rawResp, err := marshaller.Marshal(resp)
		if err != nil {
			return nil, ctx, err
		}
		return rawResp, ctx, nil

	})

	mux.Register("Greet.SendMyGift", func(req *http.Request, marshaller runtime.Marshaler, rawBody json.RawMessage) (json.RawMessage, context.Context, error) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var err error
		ctx, err = runtime.AnnotateContext(ctx, mux.RuntimeMux(), req, "/proto.Greet/SendMyGift")
		if err != nil {
			return nil, ctx, err
		}
		resp, md, err := request_Greet_SendMyGift_jsonrpc(ctx, marshaller, client, rawBody)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			return nil, ctx, err
		}
		rawResp, err := marshaller.Marshal(resp)
		if err != nil {
			return nil, ctx, err
		}
		return rawResp, ctx, nil

	})

	mux.Register("Greet.Hello2", func(req *http.Request, marshaller runtime.Marshaler, rawBody json.RawMessage) (json.RawMessage, context.Context, error) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var err error
		ctx, err = runtime.AnnotateContext(ctx, mux.RuntimeMux(), req, "/proto.Greet/Hello2")
		if err != nil {
			return nil, ctx, err
		}
		resp, md, err := request_Greet_Hello2_jsonrpc(ctx, marshaller, client, rawBody)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			return nil, ctx, err
		}
		rawResp, err := marshaller.Marshal(resp)
		if err != nil {
			return nil, ctx, err
		}
		return rawResp, ctx, nil

	})

	return nil
}
